### ISSUE TITLE
关于损失项的疑问

### ISSUE THREAD

**Issue by SpriteMisaka** [qinghai-zheng/LIBLE#2]
你好！我对损失项的实现感到疑惑。以`Demo_Artificial.py`中73~75行为例：

```python
lost_obj = (log_l - d_pre)**2
lost_obj = torch.mul(lost_obj, (0.5*torch.pow(gap, -2))) + torch.log(torch.abs(gap))
lost_obj = lost_obj.mean(1, keepdim=True)
```

首先我想确认这段是否对应论文中的式(28)？如果是，我觉得实现中有些地方不太正确：

1. `(log_l - d_pre)**2`是元素级的幂运算，这样做相当于和其他的LE文献一样计算了|| D - L ||^2，与式(28)的矩阵乘法是不一致的；

2. 式(28)中的det是否为行列式？如果是，这里用`torch.abs`也与原式不一致。

我还想请教如何得到式(28)以及该损失项如何对LE任务产生贡献。

谢谢！

**Comment by qinghai-zheng** [comment]
> 你好！我对损失项的实现感到疑惑。以`Demo_Artificial.py`中73~75行为例：
> 
> ```python
> lost_obj = (log_l - d_pre)**2
> lost_obj = torch.mul(lost_obj, (0.5*torch.pow(gap, -2))) + torch.log(torch.abs(gap))
> lost_obj = lost_obj.mean(1, keepdim=True)
> ```
> 
> 首先我想确认这段是否对应论文中的式(28)？如果是，我觉得实现中有些地方不太正确：
> 
> 1. `(log_l - d_pre)**2`是元素级的幂运算，这样做相当于和其他的LE文献一样计算了|| D - L ||^2，与式(28)的矩阵乘法是不一致的；
> 2. 式(28)中的det是否为行列式？如果是，这里用`torch.abs`也与原式不一致。
> 
> 我还想请教如何得到式(28)以及该损失项如何对LE任务产生贡献。
> 
> 谢谢！

你好，这里是对应公式（28）那一块的内容。
1. `(log_l - d_pre)**2`这里这一块是为了下面一行的计算`lost_obj = torch.mul(lost_obj, (0.5*torch.pow(gap, -2))) + torch.log(torch.abs(gap))`，这里是和其他的LE文献一样计算|| D - L ||^2不一样的，这两个过程是不一样的。`lost_obj = torch.mul(lost_obj, (0.5*torch.pow(gap, -2))) + torch.log(torch.abs(gap))`是和式子（28）的前一项对得上的，这里需要注意的是除的矩阵是一个对角矩阵，所以是对得上的。
2. 同上理，因为是对对角矩阵进行求行列式，所示对的上的。

**Comment by qinghai-zheng** [comment]
> 你好！我对损失项的实现感到疑惑。以`Demo_Artificial.py`中73~75行为例：
> 
> ```python
> lost_obj = (log_l - d_pre)**2
> lost_obj = torch.mul(lost_obj, (0.5*torch.pow(gap, -2))) + torch.log(torch.abs(gap))
> lost_obj = lost_obj.mean(1, keepdim=True)
> ```
> 
> 首先我想确认这段是否对应论文中的式(28)？如果是，我觉得实现中有些地方不太正确：
> 
> 1. `(log_l - d_pre)**2`是元素级的幂运算，这样做相当于和其他的LE文献一样计算了|| D - L ||^2，与式(28)的矩阵乘法是不一致的；
> 2. 式(28)中的det是否为行列式？如果是，这里用`torch.abs`也与原式不一致。
> 
> 我还想请教如何得到式(28)以及该损失项如何对LE任务产生贡献。
> 
> 谢谢！

你好，公式（28）那一块内容相当于对标记gap进行了建模，之前的LE任务都是直接用gap的大小直接来处理增强任务，这里基于最小化L_{gap}得到的公式（28），可以这么简单理解：类似于对算出来的每个gap大小给出权重。

感谢你对我们工作感兴趣，有其他问题欢迎随时讨论，也可以发邮件qhxjtu@163.com交流。

**Comment by SpriteMisaka** [comment]
感谢回复！根据我对回复的理解，还是想确认两件事情：

1. 这个损失项可以简单理解成是gap加权的|| D - L ||^2；

2. 对每个样本而言，式(28)中的sigma^{-2}I和sigma^{2}I都是代表样本权重的实数，而对整个矩阵而言，可以写成gap对角矩阵和|| D - L ||^2的元素级相乘。

若是这样，论文中的记号或许太复杂了。

我想知道这样理解有没有偏差，谢谢！

**Comment by qinghai-zheng** [comment]
> 感谢回复！根据我对回复的理解，还是想确认两件事情：
> 
> 1. 这个损失项可以简单理解成是gap加权的|| D - L ||^2；
> 2. 对每个样本而言，式(28)中的sigma^{-2}I和sigma^{2}I都是代表样本权重的实数，而对整个矩阵而言，可以写成gap对角矩阵和|| D - L ||^2的元素级相乘。
> 
> 若是这样，论文中的记号或许太复杂了。
> 
> 我想知道这样理解有没有偏差，谢谢！

你好，前一段时间没有及时登陆查看issue，很抱歉今天才看到并回复。
这个简单去理解这样子也没太大问题，不过实际上整个模型是从信息瓶颈的角度出发，与此同时又额外引入和处理标记gap来进行推导的，单纯考虑权重的话其实很难去直接加权，而且除了加权外，模型中后面还有一个加上的项。模型中的记号其实感觉也还可以，这些符号在模型推导过程能够把问题描述和方法讲清楚:）
